# Generated by Django 6.0.2 on 2026-02-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='书源名称')),
                ('url', models.CharField(max_length=500, unique=True, verbose_name='书源URL')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='分组')),
                ('source_type', models.IntegerField(choices=[(0, '文本'), (1, '音频'), (2, '图片'), (3, '文件')], default=0, verbose_name='类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='书源配置')),
                ('search_url', models.CharField(blank=True, max_length=500, verbose_name='搜索URL模板')),
                ('book_list_rule', models.TextField(blank=True, verbose_name='书籍列表规则')),
                ('name_rule', models.CharField(blank=True, max_length=200, verbose_name='书名规则')),
                ('author_rule', models.CharField(blank=True, max_length=200, verbose_name='作者规则')),
                ('kind_rule', models.CharField(blank=True, max_length=200, verbose_name='分类规则')),
                ('cover_url_rule', models.CharField(blank=True, max_length=200, verbose_name='封面规则')),
                ('intro_rule', models.CharField(blank=True, max_length=200, verbose_name='简介规则')),
                ('last_chapter_rule', models.CharField(blank=True, max_length=200, verbose_name='最新章节规则')),
                ('book_url_rule', models.CharField(blank=True, max_length=200, verbose_name='书籍URL规则')),
                ('book_info_init', models.TextField(blank=True, verbose_name='预处理规则')),
                ('toc_url_rule', models.CharField(blank=True, max_length=200, verbose_name='目录URL规则')),
                ('chapter_list_rule', models.TextField(blank=True, verbose_name='章节列表规则')),
                ('chapter_name_rule', models.CharField(blank=True, max_length=200, verbose_name='章节名称规则')),
                ('chapter_url_rule', models.CharField(blank=True, max_length=200, verbose_name='章节URL规则')),
                ('next_toc_url_rule', models.TextField(blank=True, verbose_name='下一页规则')),
                ('content_rule', models.TextField(blank=True, verbose_name='正文规则')),
                ('next_content_url_rule', models.TextField(blank=True, verbose_name='正文下一页规则')),
                ('web_js', models.TextField(blank=True, verbose_name='WebJs')),
                ('source_regex', models.TextField(blank=True, verbose_name='资源正则')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '停用'), ('error', '错误')], default='active', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('header', models.JSONField(blank=True, null=True, verbose_name='请求头')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '书源配置',
                'verbose_name_plural': '书源配置',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('cover_url', models.URLField(blank=True, max_length=500, verbose_name='封面URL')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('kind', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('word_count', models.CharField(blank=True, max_length=20, verbose_name='字数')),
                ('last_chapter', models.CharField(blank=True, max_length=200, verbose_name='最新章节')),
                ('book_url', models.CharField(max_length=500, unique=True, verbose_name='书籍URL')),
                ('toc_url', models.CharField(blank=True, max_length=500, verbose_name='目录URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('is_local', models.BooleanField(default=True, verbose_name='本地书籍')),
                ('from_source', models.CharField(blank=True, max_length=200, verbose_name='来源书源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'indexes': [models.Index(fields=['name'], name='books_book_name_fbe345_idx'), models.Index(fields=['author'], name='books_book_author_b941fe_idx'), models.Index(fields=['book_url'], name='books_book_book_ur_5b9e0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('search', '搜索'), ('import', '导入'), ('sync', '同步')], max_length=20, verbose_name='任务类型')),
                ('keyword', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.booksource')),
            ],
            options={
                'verbose_name': '抓取任务',
                'verbose_name_plural': '抓取任务',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('chapter_url', models.CharField(max_length=500, verbose_name='章节URL')),
                ('chapter_index', models.IntegerField(verbose_name='章节序号')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP章节')),
                ('content', models.TextField(blank=True, verbose_name='正文内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['chapter_index'],
                'indexes': [models.Index(fields=['book', 'chapter_index'], name='books_chapt_book_id_ac6063_idx')],
                'unique_together': {('book', 'chapter_url')},
            },
        ),
    ]
