# Generated by Django 6.0.2 on 2026-02-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('search', '搜索'), ('import', '导入'), ('sync', '同步')], max_length=20, verbose_name='任务类型')),
                ('keyword', models.CharField(blank=True, help_text='搜索关键词或书籍URL', max_length=200, verbose_name='关键词')),
                ('interval_type', models.CharField(choices=[('interval', '间隔执行'), ('cron', 'Cron表达式'), ('date', '单次执行')], default='interval', max_length=20, verbose_name='执行类型')),
                ('interval_seconds', models.IntegerField(default=3600, help_text='间隔多少秒执行一次', verbose_name='间隔秒数')),
                ('cron_expression', models.CharField(blank=True, help_text='分钟 小时 日期 月份 星期', max_length=100, verbose_name='Cron表达式')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('paused', '暂停'), ('completed', '已完成')], default='active', max_length=20, verbose_name='状态')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('last_result_count', models.IntegerField(default=0, verbose_name='上次结果数')),
                ('total_runs', models.IntegerField(default=0, verbose_name='总执行次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.booksource', verbose_name='书源')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('running', '运行中')], default='running', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='books.scheduledtask')),
            ],
            options={
                'verbose_name': '定时任务日志',
                'verbose_name_plural': '定时任务日志',
                'ordering': ['-start_time'],
            },
        ),
    ]
