# Generated by Django 6.0.2 on 2026-02-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_scheduledtask_scheduledtasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksource',
            name='explore_rule',
            field=models.JSONField(blank=True, default=dict, verbose_name='发现规则'),
        ),
        migrations.AddField(
            model_name='booksource',
            name='explore_url',
            field=models.TextField(blank=True, help_text='格式：分类名::URL，每行一个', verbose_name='发现URL'),
        ),
    ]
